telemetry-code-along/lib/quantum_web/router.ex
defmodule QuantumWeb.Router do
  use QuantumWeb, :router
  pipeline :browser do
    # plug :put_root_layout, {QuantumWeb.LayoutView, :app}
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug QuantumWeb.Plugs.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", QuantumWeb do
    pipe_through [:browser]
    get "/", PageController, :index
  end

  scope "/", QuantumWeb do
    pipe_through [:browser, QuantumWeb.Plugs.Guest]

    resources "/register", UserController, only: [:create, :new]
    get "/login", SessionController, :new
    post "/login", SessionController, :create
  end

  scope "/", QuantumWeb do
    pipe_through [:browser, QuantumWeb.Plugs.Auth]

    delete "/logout", SessionController, :delete

    get "/users/:id", UserController, :show
    live "/buttons", ButtonLive
  end

  # if Mix.env() == :dev do
  #   scope "/" do
  #     pipe_through :browser
  #     live_dashboard "/dashboard"
  #   end
  # end

  # Other scopes may use custom stacks.
  # scope "/api", QuantumWeb do
  #   pipe_through :api
  # end
end

telemetry-code-along/lib/quantum_web/views/layout_view.ex
defmodule QuantumWeb.LayoutView do
  use QuantumWeb, :view
end

telemetry-code-along/lib/quantum_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || "Quantum" %></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= csrf_meta_tag() %>
  </head>
  <body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="/">Quantum</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
            </ul>
            <span class="navbar-text">
              <ul class="navbar-nav mr-auto">
                <%= if signed_in?(@conn) do %>
                  <%= link "Logout", to: Routes.session_path(@conn, :delete), method: :delete %>
                <% else %>
                  <li class="nav-item active"><%= link "Log In", to: Routes.session_path(@conn, :new), method: :get, class: "nav-link" %></li>
                  <li class="nav-item active"><%= link "Sign Up", to: Routes.user_path(@conn, :new), method: :get, class: "nav-link" %></li>
                <% end %>
              </ul>
            </span>
          </div>
        </nav>
    </header>
    <main role="main" class="container" style="margin-top: 5%;">
      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>

      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>

      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

telemetry-code-along/lib/quantum_web/templates/layout/live.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || "Quantum" %></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= csrf_meta_tag() %>
  </head>
  <body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="/">Quantum</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
            </ul>
            <span class="navbar-text">
              <ul class="navbar-nav mr-auto">
                <%= if signed_in?(@socket) do %>
                  <%= link "Logout", to: Routes.session_path(@socket, :delete), method: :delete %>
                <% else %>
                  <li class="nav-item active"><%= link "Log In", to: Routes.session_path(@socket, :new), method: :get, class: "nav-link" %></li>
                  <li class="nav-item active"><%= link "Sign Up", to: Routes.user_path(@socket, :new), method: :get, class: "nav-link" %></li>
                <% end %>
              </ul>
            </span>
          </div>
        </nav>
    </header>
    <main role="main" class="container" style="margin-top: 5%;">
      <p><%= live_flash(@flash, :notice) %></p>
      <p><%= live_flash(@flash, :error) %></p>

      <%= @inner_content %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@socket, "/js/app.js") %>"></script>
  </body>
</html>